library (readr)
data <- read_csv("/Users/lihrek/Desktop/caschool.csv")
mean(data$avginc)
sd(data$avginc)
income <- data$avginc*1000
mean(income)
sd(income)
mean(data$math_scr)
sum(data$enrl_tot/data$teachers <= 20)
mean(data$math_scr[data$enrl_tot/data$teachers <= 20])
sum(data$enrl_tot/data$teachers > 20)
mean(data$math_scr[data$enrl_tot/data$teachers > 20])
sd(data$math_scr[data$enrl_tot/data$teachers <= 20])
sd(data$math_scr[data$enrl_tot/data$teachers > 20])
cov(data$avginc, data$math_scr)
cov(income, data$math_scr)
cor(data$avginc, data$math_scr)
cor(income, data$math_scr)