library(readxl)
library(estimatr)
data <- read_excel("/Users/lihrek/Desktop/ECON 21020/fertility.xlsx")
ols1 <- lm(weeksm1 ~ morekids, data = data) 
summary(ols1)
ols2 <- lm(morekids ~ samesex, data = data) 
summary(ols2)
iv1 <- iv_robust(weeksm1 ~ morekids | samesex, data = data)
summary(iv1)
iv2 <- iv_robust(weeksm1 ~ morekids + agem1 + black + hispan + othrace | samesex + agem1 + black + hispan + othrace, data = data)
summary(iv2)