library (readr)
data <- read_csv("/Users/lihrek/Desktop/earnings.csv")
ols <- lm(wages ~ fem + college + hs, data = data) 
summary(ols)
vcov(ols)
ols2 <- lm(wages ~ fem + college + sum, data = data) 
summary(ols2)
ols3 <- lm(wages ~ college + hs, data$fem == 0, data = data) 
summary(ols3)
vcov(ols3)